name: Package

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Environments
        run: |
          echo "SM_VERSION=1.11" >> $GITHUB_ENV
      
      - name: Install
        run: |
          bash scripts/install.sh
      
      - name: Set Version
        run: |
          bash scripts/date.sh
      
      - name: Compile
        run: |
          mkdir -p build/addons/sourcemod/plugins/freaks
          cd build/addons/sourcemod/scripting
          ./spcomp -E scp_sf.sp -o ../plugins/scp_sf.smx
      
      - name: Package
        run: |
          bash scripts/package.sh
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: SCPSecretFortress-${{env.DATE_VERSION}}
          path: ./build/package